### ISSUE TITLE
BRN-38 ⁃ Lifecycle Events

### ISSUE THREAD

**Issue by CypressJosh** [CypressJosh/jira-demo#33]
Business Case: 
Addressing lifecycle events unlocks the ability to begin working on solutions for iframes, multi-domain, and authentication. Each of these features rely on interacting with third-party resources, and Cypress cannot reliably interact with third-party resources without first better controlling application state. The lifecycle events work makes controlling application state more possible by introducing application resets between tests and APIs allowing users to specify application states. 

Scope:
There are four main objectives in this work:

* Between each test, reset the AUT:
  * Resetting the application should prevent “test leakage” from occurring
  * Ensures each test starts from the same initial application state
  * Users cannot opt out of resetting the application
    * Allowing opting out would undermine Cypress as a deterministic testing application. 
* Between each test, rehydrate succeeding tests with the correct state:
  * Implement APIs users can utilize to set, get, clear, restore, and use sessions (i.e. application states)
* Surface the operations Cypress performs between tests in the Test Runner
  * The Test Runner should output in the “Test Status Menu” the below operations as they occur, just as the Test Runner outputs the actions for tests:
    * clearing localStorage, sessionStorage, and cookies
    * resetting defined routes
    * removing created stubs, spies, clocks and created aliases
    * clearing the cache before the browser opens. 
* Write extensive documentation and migration guides
  * Examples of anti-patterns leading to flaky tests
  * Examples of state sharing tests migrated to the new APIs

┆Issue is synchronized with this [Jira Epic](https://cypress-io.atlassian.net/browse/BRN-38) by [Unito](https://www.unito.io/learn-more)

**Comment by brian-mann** [comment]
This is a test.
